FROM apache/spark:3.5.7-scala2.12-java17-python3-ubuntu

USER root

# --------------------------------------------------
# Версии, совместимые со Spark 3.5.x
# --------------------------------------------------
ENV HADOOP_AWS_VERSION=3.3.4
ENV AWS_SDK_VERSION=1.12.367
ENV POSTGRES_JDBC_VERSION=42.7.4

RUN curl -fSL https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
      -o /opt/spark/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar && \
    curl -fSL https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar \
      -o /opt/spark/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar && \
    curl -fSL https://jdbc.postgresql.org/download/postgresql-${POSTGRES_JDBC_VERSION}.jar \
      -o /opt/spark/jars/postgresql-${POSTGRES_JDBC_VERSION}.jar
# --------------------------------------------------
# Системные пакеты (минимум)
# --------------------------------------------------
RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# create home for spark user
RUN mkdir -p /home/spark && chown -R spark:spark /home/spark
ENV HOME=/home/spark    

# --------------------------------------------------
# Python: pip + JupyterLab
# --------------------------------------------------
RUN python3 -m pip install --upgrade pip \
    && pip install --no-cache-dir jupyterlab

# --------------------------------------------------
# Spark / PySpark env
# --------------------------------------------------
ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$PATH

ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

# --------------------------------------------------
# Spark defaults (S3 / MinIO)
# --------------------------------------------------
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

USER spark
